algoritmo "semnome"
var
    n1, n2 , m:real
inicio
      escreval("----------------------")
      escreval("      escola xyz      ")
      escreval("----------------------")
      escreval("calcule sua média")
      escreval("escreva a primeira nota: ")
      leia(n1)
      escreval("escreva a outra nota: ")
      leia(n2)
      m <- (n1+n2)/2
      escreval("A sua média escolar é: ", m)
      escreval("======================")
fimalgoritmo